# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MODEL_DIRECTORY: "models"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Rasa Train-Test Model GitHub Action
        # You may pin to the exact commit or the version.
        # uses: RasaHQ/rasa-train-test-gha@c8ef0eff3c525e3d8fc928b19bed1105073fe8f0
        uses: RasaHQ/rasa-train-test-gha@2.0.0
        with:
          # The Rasa version used to run test and train
          rasa_version: latest-full # default is latest-full
          # Run rasa train
          rasa_train: true # default is true
          # Run rasa test
          rasa_test: false # default is true
          # Fine-tune model
          fine_tune: false # optional, default is false
          # Validates domain and data files to check for possible mistakes
          data_validate: true # default is true
          
      - name: Upload model
        #if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@master
        with:
          name: model
          path: models
        
      - name: Get path to model
        run: |
          ls -R
          echo "MODELNAME=${{ env.MODEL_DIRECTORY }}/$(ls ${{ env.MODEL_DIRECTORY }})" >> $GITHUB_ENV

      - name: Upload Model to Rasa
        run: |
          curl -k -F "model=@${MODELNAME}" "${RASA_URL}/api/projects/default/models"
